backend:
  name: github
  repo: Alvin-TW/Alvin-TW.github.io
  branch: master

media_folder: content/asserts
public_folder: /asserts

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    slug: '{{slug}}'
    identifier_field: fileName
    fields:
      - {label: "File Name", name: "fileName", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: 'Date', name: 'date', widget: 'datetime' }
      - {label: "Tags", name: "tags", widget: "select", multiple: true,
          options: [
            "javascript",
            "html",
            "css"
          ]
        }
      - {label: "Body", name: "body", widget: "markdown"}