backend:
  name: github
  repo: Alvin-TW/Alvin-TW.github.io
  branch: master

media_folder: "content/asserts"
public_folder: "/asserts"

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", field: {name: tag, label: Tag, widget: string}}
      - {label: "Content", name: "body", widget: "markdown"}