backend:
  name: github
  repo: Alvin-TW/Alvin-TW.github.io
  branch: master
  media_folder: "static/images/uploads"
  public_folder: "/images/uploads"
  collections:
    - name: blog
      label: Blog
      folder: content/_posts
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Date", name: "date", widget: "datetime"}
        - {label: "Thumbnail", name: "thumbnail", widget: "image"}
        - {label: "Tags", name: "tags", widget: "select", multiple: true,
          options: [
              "JavaScript",
              "Css",
              "Html",
            ],
            default: ["JavaScript"]
          }
        - {label: "Content", name: "body", widget: "markdown"}