backend:
  name: github
  repo: Alvin-TW/Alvin-TW.github.io
  branch: master

media_folder: "content/asserts"
public_folder: "../asserts"

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "FeaturedImage", name: "featuredImage", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "select", multiple: true,
          options: [
            "javascript",
            "html",
            "css"
          ]
        }
      - {label: "Content", name: "body", widget: "markdown"}